language: cpp

before_install:
    - sudo apt update
    - sudo apt install libboost-filesystem-dev
    - sudo apt install libboost-thread-dev
    - sudo apt install libassimp-dev
    - sudo apt install libglew-dev
    - sudo apt install assimp-utils

compiler:
    - gcc

install:
    - cd /usr/local
    - sudo wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz
    - sudo tar -xzf SFML-2.4.2-linux-gcc-64-bit.tar.gz
    - sudo cp -r SFML-2.4.2/include .
    - sudo cp -r SFML-2.4.2/lib .
    - sudo cp -r SFML-2.4.2/share .
    - sudo rm -rf SFML-2.4.2

    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

    - |
        if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
            CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
            mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
            export PATH=${DEPS_DIR}/cmake/bin:${PATH}
        fi

    - sudo wget https://github.com/g-truc/glm/archive/0.9.8.4.tar.gz
    - sudo tar -xzf 0.9.8.4.tar.gz
    - cd glm-0.9.8.4/cmake
    - sudo cmake ..
    - sudo make install

    - cd ${TRAVIS_BUILD_DIR}

script:
    - mkdir build
    - cd build
    - ${DEPS_DIR}/cmake/bin/cmake .. && make
