language: cpp

before_install:
    - sudo add-apt-repository ppa:sonkun/sfml-stable
    - sudo apt install sfml
    - sudo apt install libboost-filesystem-dev
    - sudo apt install libboost-thread-dev
    - sudo apt install libassimp-dev
    - sudo apt install libglew-dev
    - sudo apt install assimp-utils

compiler:
    - gcc

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

    - |
        if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
            CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
            mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
            export PATH=${DEPS_DIR}/cmake/bin:${PATH}
        fi

    - cd ..

script:
    - mkdir build
    - cd build
    - ${DEPS_DIR}/cmake/bin/cmake .. && make
